name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # lock があるなら ci、無いなら install
      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # あなたのビルドコマンドに合わせて変更（例：npm run build）
      - name: Build
        run: |
          npm run build

      # ★ dist/index.html に r4-inline を自動追記（未挿入時のみ）
      - name: Inject r4-inline into dist/index.html if missing
        shell: bash
        run: |
          set -e
          f="dist/index.html"
          test -f "$f"
          if ! grep -q "2025-08-19 r4-inline" "$f"; then
            awk 'BEGIN{inj=0}
                 /<\/body>/{print "<script>(function(){const V=\"Siwon 20250807 / 2025-08-19 r4-inline\";try{if(!location.search.includes(\"_v=\")){const u=new URL(location.href);u.searchParams.set(\"_v\",\"2025.08.19-r4\");location.replace(u.toString());return;}}catch(e){}const B=[/初級|中級|上級/g,/難易度/g,/ガイドモード/g,/プルダウン/g,/自由記述/g,/カテゴリ選択/g,/個別評価|設問別評価/g],bo=/(初級|中級|上級|難易度|ガイドモード|プルダウン|自由記述|カテゴリ選択|個別評価|設問別評価)/;function S(s){return B.reduce((t,r)=>t.replace(r,\"\") ,String(s||\"\"))}function U(){if(!document.querySelector(\"[data-boot-min='\''1'\'']\")){const d=document.createElement(\"div\");d.setAttribute(\"data-boot-min\",\"1\");d.style.cssText=\"margin:16px 12px;padding:12px;border:1px dashed #bbb;border-radius:8px\";d.innerText=\"シヲン20250807 起動\n1=開始 / 9=終了\n入力は数値のみ\";document.body.insertBefore(d,document.body.firstChild);}}function BZ(){if(document.getElementById(\"siwon-badge\"))return;const b=document.createElement(\"div\");b.id=\"siwon-badge\";b.textContent=V;b.style.cssText=\"position:fixed;right:8px;bottom:8px;padding:4px 8px;border:1px solid #ccc;background:#fff;font-size:12px;opacity:.85;z-index:9999\";document.body.appendChild(b);}function SC(r){if(!r)r=document.body;const w=document.createTreeWalker(r,NodeFilter.SHOW_TEXT,null);let n;while(n=w.nextNode()){if(bo.test(n.nodeValue))n.nodeValue=S(n.nodeValue)}r.querySelectorAll(\"*\").forEach(e=>{if(e.children.length===0&&e.innerText&&bo.test(e.innerText))e.innerText=S(e.innerText)})}function SK(){const t=(document.body.innerText||\"\");if(/難易度|初級|中級|上級/.test(t)){document.querySelectorAll(\"*\").forEach(e=>{if(e&&e.innerText&&/難易度|初級|中級|上級/.test(e.innerText)){e.innerHTML=\"\"}})}}function boot(){U();BZ();SC(document.body);SK()}if(document.readyState===\"loading\"){document.addEventListener(\"DOMContentLoaded\",boot)}else{boot()}const mo=new MutationObserver(m=>{let k=false;for(const x of m){if(x.addedNodes&&x.addedNodes.length){k=true;break}if(x.type===\"characterData\"){k=true;break}}if(k){SC(document.body);SK();U();BZ()}});mo.observe(document.documentElement,{subtree:true,childList:true,characterData:true});})();</script>"; inj=1}
                 {print}
                ' "$f" > "$f.tmp"
            mv "$f.tmp" "$f"
          fi

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
